### ISSUE TITLE
Getting error with running test (npm test)

### ISSUE THREAD

**Issue by mpirbhoy** [liamks/csc490-a3#5]
Searched the web extensively but couldn't find a solution. Help is much appreciated. The error is below:-

> ./node_modules/karma/bin/karma start karma.conf.js

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.

**Comment by liamks** [comment]
In `package.json` I specify to npm how to `test` the code: 

```
  "scripts": {
    "test": "./node_modules/karma/bin/karma start karma.conf.js"
  }
```

I'm using a relative path, which may only work with mac os x and linux. Here's what I'd recommend doing:
1. install karma globally `npm install karma -g` (if you're on mac os x, add `sudo`).
2. Then run `karma start karma.conf.js`

If that doesn't work then try googling for how to install Karma globally on windows.

**Comment by jasonwcfan** [comment]
I installed karma globally but when I try to run `karma start karma.conf.js` I get the following error:

```
C:\Users\jason\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\inject                                                      or.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:jasmine"! (Resolving: framework:jasmine)
    at error (C:\Users\jason\AppData\Roaming\npm\node_modules\karma\node_modules                                                      \di\lib\injector.js:22:12)
    at Object.parent.get (C:\Users\jason\AppData\Roaming\npm\node_modules\karma\                                                      node_modules\di\lib\injector.js:9:13)
    at get (C:\Users\jason\AppData\Roaming\npm\node_modules\karma\node_modules\d                                                      i\lib\injector.js:54:19)
    at C:\Users\jason\AppData\Roaming\npm\node_modules\karma\lib\server.js:137:2                                                      0
    at Array.forEach (native)
    at Server._start (C:\Users\jason\AppData\Roaming\npm\node_modules\karma\lib\                                                      server.js:136:21)
    at invoke (C:\Users\jason\AppData\Roaming\npm\node_modules\karma\node_module                                                      s\di\lib\injector.js:75:15)
    at Server.start (C:\Users\jason\AppData\Roaming\npm\node_modules\karma\lib\s                                                      erver.js:101:18)
    at Object.exports.run (C:\Users\jason\AppData\Roaming\npm\node_modules\karma                                                      \lib\cli.js:235:26)
    at Object.<anonymous> (C:\Users\jason\AppData\Roaming\npm\node_modules\karma                                                      \bin\karma:3:23)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)

```
